version: '3.5'
services:
  namesrv:
    image: rocketmqinc/rocketmq:4.4.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ../data/namesrv/logs:/home/rocketmq/logs
      - ../data/namesrv/store:/home/rocketmq/store
    command: sh mqnamesrv
    networks:
      rmq:
        aliases:
          - namesrv

  broker:
    image: rocketmqinc/rocketmq:4.4.0
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - ../data/broker/logs:/home/rocketmq/logs
      - ../data/broker/store:/home/rocketmq/store
      - ./rocketmq/broker/conf/broker.conf:/opt/rocketmq-4.4.0/conf/broker.conf
    environment:
      NAMESRV_ADDR: "namesrv:9876"
      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
    command: sh mqbroker -n namesrv:9876 -c ../conf/broker.conf
    depends_on:
      - namesrv
    networks:
      rmq:
        aliases:
          - broker

  rmqconsole:
    image: styletang/rocketmq-console-ng
    container_name: rmqconsole
    ports:
      - 8070:8080
    environment:
      JAVA_OPTS: "-Drocketmq.config.namesrvAddr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    volumes:
      - ../data/consolelogs:/root/logs/consolelogs
    depends_on:
      - namesrv
    networks:
      rmq:
        aliases:
          - rmqconsole

networks:
  rmq:
    name: rmq
    driver: bridge