version: '3.3'
services:
  seata:
    image: romeoblog/seata-server:0.7.1
    container_name: seata-server
    environment:
      - SEATA_PORT=8091
      - SEATA_MODE=db
    volumes:
      - ../data/seata-server/logs/:/root/logs/seata
    ports:
      - 8091:8091
      - 9898:9898